### ISSUE TITLE
Possibly add link to "UI/UX VR"

### ISSUE THREAD

**Issue by cvan** [wizztjh/awesome-WebVR#6]
There's https://github.com/omgmog/ui-ux-vr - some of it's specific to WebVR but not all

**Comment by tjiahen** [comment]
Great Idea. I think we should create a "UI/UX VR" sub section and link it to them. It is a good collection of UI/UX resources. 

WebVR and Native VR will use the same UI/UX i presume.

**Comment by tjiahen** [comment]
added the link
